apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-config.yaml
  - platform-gateway-advertisement.yaml
  - platform-gateway-vips.yaml
  - peer-config.yaml
  - platform-networking-ns.yaml
  - internal-gateway.yaml
  - public-gateway.yaml
  - tenant-control-plane-advertisement.yaml
  - tenant-control-plane-vips.yaml
