apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: tenant-control-plane-vips
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchLabels:
          platform.sbrtech.xyz/vip-pool: tenant-control-plane
