apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-letsencrypt
spec:
  acme:
    email: srupert@sbrtech.xyz
    privateKeySecretRef:
      name: cloudflare-letsencrypt-account-key
    
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
