apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-control-plane
spec:
  provider:
    onepassword:
      connectHost: https://opc.infra.int.sbrtech.xyz:8080
      vaults:
        Control Plane: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-access-token
            namespace: external-secrets
            key: token
