apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 30m
  timeout: 10m
  releaseName: crossplane
  targetNamespace: crossplane-system

  chart:
    spec:
      chart: crossplane
      version: "2.4.0"
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
        namespace: crossplane-system

  driftDetection:
    mode: enabled

  install:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 5m

  upgrade:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
