apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
  namespace: external-dns
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-control-plane

  target:
    name: external-dns-cloudflare
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: api-token
      remoteRef:
        key: cloudflare-api-token
        property: credential
