apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-rfc2136
  namespace: external-dns
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-control-plane

  target:
    name: external-dns-rfc2136
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: tsig-secret
      remoteRef:
        key: external-dns-control-plane
        property: credential
