apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: kubeadm
  namespace: capi-kubeadm-control-plane-system
spec:
  version: v1.14.2
  fetchConfig:
    url: https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.14.2/control-plane-components.yaml
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: kamaji
  namespace: kamaji-system
spec:
  version: v0.21.0
  fetchConfig:
    url: https://github.com/clastix/cluster-api-control-plane-provider-kamaji/releases/download/v0.21.0/control-plane-components.yaml
