apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - core.yaml
  - bootstrap.yaml
  - control-plane.yaml
  - infrastructure.yaml
  - ipam.yaml
  - addon.yaml
