apiVersion: v1
kind: Namespace
metadata:
  name: capi-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-bootstrap-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-kubeadm-control-plane-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capmox-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-ipam-in-cluster-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: caaph-system
