apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-file
provisioner: csi.truenas.io
parameters:
  protocol: "nfs"
  pool: "ssd-pool"
  datasetPath: "k8s/control-plane/nfs"
  compression: "LZ4"
  nfs.mountOptions: "hard,nfsvers=4.1"
  nfs.rootSquash: "false"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
