apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
  # - infrastructure.yaml
  # - crossplane-core.yaml
  # - crossplane-packages.yaml
  # - crossplane-configuration.yaml
  # - crossplane-instances.yaml