apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vyos-bgp-auth
  namespace: kube-system
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-control-plane

  target:
    name: vyos-bgp-auth
    creationPolicy: Owner
    deletionPolicy: Retain

  data:
    - secretKey: password
      remoteRef:
        key: vyos-control-plane-bgp-auth
        property: credential
