apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-garage-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-control-plane
  target:
    name: velero-garage-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .accessKeyId }}
          aws_secret_access_key={{ .secretAccessKey }}
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: velero-s3-bucket-key-control-plane
        property: username
    - secretKey: secretAccessKey
      remoteRef:
        key: velero-s3-bucket-key-control-plane
        property: password
